before:
  hooks:
    - go mod tidy

builds:
- goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  env:
    - CGO_ENABLED=0
  ignore:
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: arm
    - goos: linux
      goarch: arm
      goarm: 7


dockers:
  - image_templates:
    - "ghcr.io/natpowning/victron-exporter:latest-amd64"
    - "ghcr.io/natpowning/victron-exporter:{{ .Tag }}-amd64"
    goos: linux
    goarch: amd64
    extra_files:
      - ./entrypoint.sh
  - image_templates:
    - "ghcr.io/natpowning/victron-exporter:latest-arm64"
    - "ghcr.io/natpowning/victron-exporter:{{ .Tag }}-arm64"
    goos: linux
    goarch: arm64
    extra_files:
      - ./entrypoint.sh
  - image_templates:
    - "ghcr.io/natpowning/victron-exporter:latest-arm64v8"
    - "ghcr.io/natpowning/victron-exporter:{{ .Tag }}-arm64v8"
    goos: linux
    goarch: arm64
    goarm: 8
    extra_files:
      - ./entrypoint.sh

docker_manifests:
  - name_template: "ghcr.io/natpowning/victron-exporter:latest"
    image_templates:
    - "ghcr.io/natpowning/victron-exporter:latest-amd64"
    - "ghcr.io/natpowning/victron-exporter:latest-arm64"
    - "ghcr.io/natpowning/victron-exporter:latest-arm64v8"

  - name_template: "ghcr.io/natpowning/victron-exporter:{{ .Tag }}"
    image_templates:
    - "ghcr.io/natpowning/victron-exporter:{{ .Tag }}-amd64"
    - "ghcr.io/natpowning/victron-exporter:{{ .Tag }}-arm64"
    - "ghcr.io/natpowning/victron-exporter:{{ .Tag }}-arm64v8"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
